In [41]:
class MeraLr:
    def __init__(self):
        self.m=None
        self.b=None
        
    def fit(self,X_train,y_train):
        num=0
        dem=0
        for i in range(X_train.shape[0]):
            num=num+(X_train[i]-X_train.mean())*(y_train[i]-y_train.mean())
            dem=dem+(X_train[i]-X_train.mean())**2
        self.m=num/dem
        self.b=y_train.mean()-(self.m*X_train.mean())
        
        print("Model is fitted with m=",self.m," and b=",self.b)
            
        
    def predict(self,X_test):
        return self.m*X_test+self.b

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [3]:
df=pd.read_csv("placement.csv")
df.head()

,cgpa,package
0,6.89,3.26
1,5.12,1.98
2,7.82,3.25
3,7.42,3.67
4,6.94,3.57


In [28]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,0:1].values,df.iloc[:,-1].values,test_size=0.2,random_state=42)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((160, 1), (40, 1), (160,), (40,))

In [30]:
X_train

array([[7.18],
       [7.21],
       [8.62],
       [6.53],
       [5.12],
       [6.93],
       [7.15],
       [7.48],
       [4.85],
       [7.61],
       [5.84],
       [6.75],
       [7.89],
       [5.91],
       [7.12],
       [8.44],
       [7.91],
       [7.69],
       [6.93],
       [7.11],
       [9.31],
       [5.98],
       [8.1 ],
       [8.94],
       [6.87],
       [7.39],
       [5.95],
       [8.11],
       [7.11],
       [5.64],
       [9.26],
       [6.78],
       [5.53],
       [6.89],
       [7.4 ],
       [6.94],
       [8.31],
       [7.19],
       [7.95],
       [5.42],
       [7.82],
       [8.99],
       [6.07],
       [6.26],
       [7.28],
       [4.79],
       [7.3 ],
       [5.99],
       [6.19],
       [5.48],
       [6.14],
       [6.76],
       [6.71],
       [6.35],
       [6.61],
       [7.89],
       [8.71],
       [6.73],
       [5.42],
       [5.23],
       [6.94],
       [6.96],
       [6.93],
       [5.84],
       [7.77],
       [6.17],
       [5.

In [31]:
y_train

array([3.  , 3.24, 4.36, 2.71, 2.01, 2.46, 3.49, 2.83, 1.54, 2.77, 1.87,
       2.56, 2.99, 2.6 , 2.99, 4.03, 3.15, 3.83, 2.51, 2.61, 4.37, 2.84,
       3.89, 3.65, 2.87, 2.65, 2.54, 4.06, 2.66, 2.1 , 3.79, 3.11, 2.55,
       2.7 , 2.88, 2.37, 3.42, 2.4 , 4.14, 2.25, 3.25, 4.6 , 2.26, 2.44,
       3.48, 1.48, 3.33, 2.84, 2.69, 1.61, 2.3 , 3.18, 3.52, 2.73, 2.6 ,
       3.67, 4.08, 2.6 , 2.16, 1.73, 3.57, 3.08, 3.04, 2.18, 4.06, 2.42,
       1.86, 2.09, 4.1 , 2.46, 3.98, 3.26, 3.96, 3.99, 2.35, 2.3 , 2.92,
       1.86, 3.91, 2.24, 4.02, 3.54, 3.09, 3.13, 3.65, 2.48, 3.14, 2.21,
       2.2 , 3.33, 3.52, 3.26, 2.42, 2.85, 2.76, 3.89, 3.67, 2.82, 2.61,
       2.58, 2.72, 3.63, 3.18, 4.62, 3.44, 3.42, 2.48, 3.76, 2.14, 3.49,
       3.23, 3.89, 2.72, 2.31, 2.89, 3.31, 3.76, 2.01, 2.09, 3.62, 3.5 ,
       2.83, 3.6 , 2.72, 4.25, 3.09, 2.59, 4.43, 2.57, 3.09, 4.09, 1.48,
       2.93, 1.94, 2.93, 3.75, 3.12, 2.43, 2.7 , 1.94, 1.98, 4.11, 3.67,
       2.49, 2.76, 3.  , 3.24, 3.33, 3.55, 3.44, 3.

In [42]:
lr=MeraLr()
lr.fit(X_train,y_train)

Model is fitted with m= [0.57425647]  and b= [-1.02700694]


In [46]:
lr.predict([5.12])

array([1.9131862])

In [34]:
X_train.shape[0]

160

In [35]:
X_train.mean()

np.float64(7.005375000000001)

In [36]:
X_train[0]

array([7.18])