In [2]:
# numpy is the python library for numerical computations that provides support for arrays and matrices 

import numpy as np

arr1= np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)

1D Array: [1 2 3 4 5]


In [5]:
arr2= np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)
print("Shape of 2D Array:", arr2.shape)

2D Array:
 [[1 2 3]
 [4 5 6]]
Shape of 2D Array: (2, 3)


In [4]:
arr3=np.arange(0,10,2).reshape(5,1)
print("Array with values from 0 to 10 with step 2:", arr3)

Array with values from 0 to 10 with step 2: [[0]
 [2]
 [4]
 [6]
 [8]]


In [11]:
np.ones_array= np.ones((3,3))
print("3x3 Array of Ones:\n", np.ones_array)

3x3 Array of Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
np.zeros_array= np.zeros((2,4))
print("2x4 Array of Zeros:\n", np.zeros_array)

2x4 Array of Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
np.eye_array= np.eye(4)
print("4x4 Identity Matrix:\n", np.eye_array)

4x4 Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:
#element wise add, subtract, multiply, divide

a= np.array([10,20,30,40])
b= np.array([1,2,3,4])
print("Element-wise Addition:", a + b)
print("Element-wise Subtraction:", a - b)
print("Element-wise Multiplication:", a * b)
print("Element-wise Division:", a / b)

Element-wise Addition: [11 22 33 44]
Element-wise Subtraction: [ 9 18 27 36]
Element-wise Multiplication: [ 10  40  90 160]
Element-wise Division: [10. 10. 10. 10.]


In [ ]:
c=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Original Array:\n", c)
#Slicing
print("Sliced Array (first two rows and first two columns):\n", c[0:2, 0:2])
#Indexing
print("Element at (2,3):", c[2,3])
print("First Row:", c[0,:])
print("first Column:", c[:,0])
print("Last Column:", c[:,-1])
print("Last Row:", c[-1,:])
print("first element at (0,0)",c[0,0])
print('2,3,6,7= ', c[0:2,1:3])



Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Sliced Array (first two rows and first two columns):
 [[1 2]
 [5 6]]
Element at (2,3): 12
First Row: [1 2 3 4]
first Column: [1 5 9]
Last Column: [ 4  8 12]
Last Row: [ 9 10 11 12]
first element at (0,0) 1
2,3,6,7=  [[2 3]
 [6 7]]


In [34]:
d=np.array([1,2,3,4,5,6,7,8,9,10])
Mean=np.mean(d)
print(Mean)

Median=np.median(d)
print(Median)

stdd=np.std(d)
print(stdd)

vrd=np.var(d)
print(vrd)


5.5
5.5
2.8722813232690143
8.25


In [40]:
import numpy as np
data1=np.array([1,2,3,4,5,6,7,8,9,10])
data1=[data1>5]

