In [1]:
import numpy as np          


In [3]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [4]:
a=[1,2,3.5,"ram"]

In [ ]:
np.array(a)   # converted all to string 

array(['1', '2', '3.5', 'ram'], dtype='<U32')

In [6]:
a=[1,2,3.5]

In [ ]:
np.array(a)   # converted all to float  this is one dimenson that is called vector

array([1. , 2. , 3.5])

In [ ]:
l=[[1,2,3],[4,5,6],[7,8,9]]  # list doesnot support multi-dimention 
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(l) # it support multi-dimension(2D)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
# array generate fun
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [13]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((6,6))  # 6x6 

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr.shape

(3, 3)

In [20]:
arr.size

9

In [21]:
arr.min()

np.int64(1)

In [22]:
arr.max()

np.int64(9)

In [23]:
arr.sum()

np.int64(45)

In [ ]:
np.sum(arr,axis=0) # sum of each colmn

array([12, 15, 18])

In [ ]:
np.sum(arr,axis=1)  # sum of row

array([ 6, 15, 24])

In [27]:
#reshape and resizing
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [30]:
arr=arr.reshape(6,5) # used to cnvert the shape like 1D to 2D

In [31]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [33]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [36]:
arr[0]

array([1, 2, 3, 4, 5])

In [38]:
arr[0,0]

np.int64(1)

In [40]:
arr[0,4]

np.int64(5)

In [48]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])